/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/
#include "DIALOG.h"
#include "imageIT2R.c"
#include "stdio.h"

extern char RxChar;

// USER START (Optionally insert additional includes)
// USER END




char longi=0, lati=0;


extern WM_HWIN hDlg;


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0        (GUI_ID_USER + 0x08)
#define ID_IMAGE_0        (GUI_ID_USER + 0x09)
#define ID_TEXT_0       (GUI_ID_USER + 0x0A)
#define ID_TEXT_1       (GUI_ID_USER + 0x0B)
#define ID_TEXT_2       (GUI_ID_USER + 0x0C)
#define ID_TEXT_3       (GUI_ID_USER + 0x0E)
#define ID_TEXT_4       (GUI_ID_USER + 0x0F)
#define ID_CHECKBOX_0       (GUI_ID_USER + 0x10)
#define ID_CHECKBOX_1       (GUI_ID_USER + 0x13)
#define ID_TEXT_5       (GUI_ID_USER + 0x14)
#define ID_TEXT_6       (GUI_ID_USER + 0x15)
#define ID_IMAGE_1       (GUI_ID_USER + 0x19)
#define ID_IMAGE_2       (GUI_ID_USER + 0x1A)

#define ID_IMAGE_0_IMAGE_0       0x00
#define ID_IMAGE_1_IMAGE_0       0x01
#define ID_IMAGE_2_IMAGE_0       0x02

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       _acImage_0, "C:\Etudiants\IT2R Projet\IT2R Projet Supervision\logo\IT2R2.bmp", ID_IMAGE_0_IMAGE_0
*/


/*********************************************************************

// USER START (Optionally insert additional static data)
// USER END

*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { IMAGE_CreateIndirect, "logo", ID_IMAGE_0, 313, 18, 156, 46, 0, 0, 0 },
  { TEXT_CreateIndirect, "supervision", ID_TEXT_0, 40, 26, 200, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Phares", ID_TEXT_1, 50, 170, 201, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Portes", ID_TEXT_2, 50, 200, 190, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "GPS", ID_TEXT_3, 350, 104, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Longitude ", ID_TEXT_4, 220, 144, 240, 20, 0, 0x64, 0 },
  { CHECKBOX_CreateIndirect, "Phare_b", ID_CHECKBOX_0, 2, 170, 40, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Porte_b", ID_CHECKBOX_1, 2, 200, 40, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Latitude", ID_TEXT_5, 220, 184, 240, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Présence_obst", ID_TEXT_6, 50, 230, 181, 20, 0, 0x64, 0 },
  { IMAGE_CreateIndirect, "Gauche", ID_IMAGE_1, 20, 75, 61, 55, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Droite", ID_IMAGE_2, 88, 75, 50, 50, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/
static const void * _GetImageById(U32 Id, U32 * pSize) {
  switch (Id) {
  case ID_IMAGE_0_IMAGE_0:
    *pSize = sizeof(_acImage_0);
    return (const void *)_acImage_0;
  }
  return NULL;
}

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  const void * pData;
  WM_HWIN      hItem;
  U32          FileSize;
  int          NCode;
  int          Id;
	
	char tab[50];
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'logo'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    pData = _GetImageById(ID_IMAGE_0_IMAGE_0, &FileSize);
    IMAGE_SetBMP(hItem, pData, FileSize);
    //
    // Initialization of 'supervision'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "Supervision");
    //
    // Initialization of 'Phares'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "Phares :");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Portes'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "Portes :");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'GPS'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem, "GPS ");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Longitude '
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "Longitude: ");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Phare_b'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "ON");
    //
    // Initialization of 'Porte_b'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
    CHECKBOX_SetText(hItem, "ON");
    //
    // Initialization of 'Latitude'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetText(hItem, "Latitude : ");
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Présence_obst'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetText(hItem, "Présence ");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Gauche'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
    pData = _GetImageById(ID_IMAGE_1_IMAGE_0, &FileSize);
    IMAGE_SetBMP(hItem, pData, FileSize);
    //
    // Initialization of 'Droite'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
    pData = _GetImageById(ID_IMAGE_2_IMAGE_0, &FileSize);
    IMAGE_SetBMP(hItem, pData, FileSize);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_CHECKBOX_0: // Notifications sent by 'Phare_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);	
				if(CHECKBOX_IsChecked (hItem) == 0)
						{
						hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
						TEXT_SetFont(hItem, GUI_FONT_20_1);
						TEXT_SetText(hItem, "Phares : Eteints !");
						TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
						TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
							
						}
					else if (CHECKBOX_IsChecked (hItem) == 1)
					{
						hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
						TEXT_SetFont(hItem, GUI_FONT_20_1);
						TEXT_SetText(hItem, "Phares : Allumés !");
						TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
						TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000FF80));
					}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_1: // Notifications sent by 'Porte_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
				if(CHECKBOX_IsChecked (hItem) == 0)
						{
						hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
						TEXT_SetFont(hItem, GUI_FONT_20_1);
						TEXT_SetText(hItem, "Portes : Fermées !");
						TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
						TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
						}
					else if (CHECKBOX_IsChecked (hItem) == 1)
					{
						hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
						TEXT_SetFont(hItem, GUI_FONT_20_1);
						TEXT_SetText(hItem, "Portes : Ouvertes !");
						TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
						TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
					}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
					
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
//		case WM_USER:
//				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);		// Longitude valeur
//				TEXT_SetFont(hItem, GUI_FONT_16_1);
//				sprintf(tab,"Longitude : %c", RxChar);
//				TEXT_SetText(hItem,tab );
		
				
			
		
//				if (test[0]=='0')
//				{
//					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);              // Obstacle detection
//					TEXT_SetText(hItem, "Présence obstacle non détecté !! ");
//					TEXT_SetFont(hItem, GUI_FONT_20_1);
//					TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000FF80));
//				}
//				else if (test[0]=='1')
//				{
//					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);         
//					TEXT_SetText(hItem, "Présence obstacle détecté !! ");
//					TEXT_SetFont(hItem, GUI_FONT_20_1);
//					TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
//				}
//				
//				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);		// Longitude valeur
//				TEXT_SetFont(hItem, GUI_FONT_16_1);
//				sprintf(longitude,"Longitude : %d",longi);
//				TEXT_SetText(hItem, longitude);
//				
//				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);		// Latitude valeur
//				TEXT_SetFont(hItem, GUI_FONT_16_1);
//				sprintf(latitude,"Latitude : %d",lati);
//				TEXT_SetText(hItem, latitude);
			
  // USER END
  
		case WM_USER:
		{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);		// Latitude valeur
				sprintf(tab,"Latitude : %c", RxChar);
				TEXT_SetText(hItem,tab );
				TEXT_SetFont(hItem, GUI_FONT_16_1);
		}
		break;
		
		default:
    WM_DefaultProc(pMsg);
    break;
  }
	
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
